name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        pip install -r test-requirements.txt
    
    - name: Run tests before release
      run: |
        python -m pytest tests/ -v
    
    - name: Build package
      run: |
        python -m build
    
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build_and_test
    permissions:
      contents: write
    
    steps:
    - name: Download package artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
        
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}